
# 你的求职方向，比如：前端开发工程师等
title: 前端开发工程师等
# 你的美照地址
logo: asserts/images/me.jpg
# 你的名字
name: 张三
# 你的联系方式
phone: 188888888888
# 你的邮箱
email: LeBron@unkown.com
# 你目前的住址
address: 北京中南海
# 你毕业院校
school: 清华大学
# 你的专业
profession: 国际贸易与经济
# 你的学位
degree: 硕士学位
# 你获得过的证书或奖励
credential: 英语六级/计算机三级
